export  const SITE_LOADING= 'SITE_LOADING';
export  const SITE_SUCCESS= 'SITE_SUCCESS';
export  const SITE_ERROR= 'SITE_ERROR';

export  const PROJECTS_LOADING= 'PROJECTS_LOADING';
export  const PROJECTS_SUCCESS= 'PROJECTS_SUCCESS';
export  const PROJECTS_ERROR= 'PROJECTS_ERROR';

export  const PROJECT_LOADING= 'PROJECT_LOADING';
export  const PROJECT_SUCCESS= 'PROJECT_SUCCESS';
export  const PROJECT_ERROR= 'PROJECT_ERROR';

